### ISSUE TITLE
Runtime error on Java 21

### ISSUE THREAD

**Issue by tjake** [apangin/nalim#10]
Same code works with Java 20

```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalArgumentException: nmethod entry barrier is missing [in thread "microbench.SimilarityBench.a_dotProductNalim-jmh-worker-5"]
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.CompilerToVM.installCode0(Native Method)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.CompilerToVM.installCode(CompilerToVM.java:549)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:139)
	at jdk.internal.vm.ci/jdk.vm.ci.code.CodeCacheProvider.setDefaultCode(CodeCacheProvider.java:67)
	at one.nalim.Linker.installCode(Linker.java:174)
	at one.nalim.Linker.linkMethod(Linker.java:121)
	at one.nalim.Linker.linkMethod(Linker.java:93)
	at one.nalim.Linker.linkClass(Linker.java:77)
	at io.github.jbellis.jvector.vector.Jvector.<clinit>(Jvector.java:14)
	... 12 more

```

**Comment by apangin** [comment]
The fix is understood. JDK 21 support is not the priority right now though.

**Comment by husker-dev** [comment]
@apangin 
Should we expect any updates?

I tried to dig around on my own, but I don't have enough knowledge of assembly.

Found this test case in jdk sources. 
It places nmethod barries, but also does a lot of other work.

https://github.com/openjdk/jdk/blob/37dc1be67d4c15a040dc99dbc105c3269c65063d/test/hotspot/jtreg/compiler/jvmci/jdk.vm.ci.code.test/src/jdk/vm/ci/code/test/amd64/AMD64TestAssembler.java#L139

**Comment by husker-dev** [comment]
All I got is adding `Site` with nmethod berrier to the method call.
But it doesn't work.

There must be something in the argument instead of zero:

```java
HotSpotVMConfigAccess config = new HotSpotVMConfigAccess(HotSpotJVMCIRuntime.runtime().getConfigStore());

int MARKID_ENTRY_BARRIER_PATCH = config.getConstant("CodeInstaller::ENTRY_BARRIER_PATCH", Integer.class);

new HotSpotCompiledNmethod(
    // ...
    new Site[] { new Mark(0, MARKID_ENTRY_BARRIER_PATCH) }
    //...
}
 ```

```
nmethod entry barrier is malformed: Addr: 0x000001a4a2b3c360 Code: 0x48 expected 0x41
```

**Comment by husker-dev** [comment]
I managed to get it working!

I wrote the following code in AMD64WindowsCallingConvention:
```java
public void emitPrologue(ByteBuffer buf) {
    // cmp dword ptr 0, 0x00000000
    buf.put((byte)0x41);
    buf.put((byte)0x81);
    buf.put((byte)0x7f);
    buf.put((byte)0);
    buf.putInt(0);
}
```

Then, before inserting the asm code, you need to call `emitPrologue`.

And when creating the HotSpotCompiledNmethod, added the following:
```java
HotSpotVMConfigAccess config = new HotSpotVMConfigAccess(HotSpotJVMCIRuntime.runtime().getConfigStore());

int MARKID_ENTRY_BARRIER_PATCH = config.getConstant("CodeInstaller::ENTRY_BARRIER_PATCH", Integer.class);

new HotSpotCompiledNmethod(
    // ...
    new Site[] { new Mark(0, MARKID_ENTRY_BARRIER_PATCH) }
    //...
}
```



As I understand it, JVMCI checks the first three bytes for the "cmp dword ptr" instruction (for amd64). 
If you add these three bytes and create an instruction that does nothing useful, the following code will work.

**Comment by avduckart** [comment]
Hi, @husker-dev 

I solved this problem in the same way. I looked at the JVM Hotspot code in JDK 21, and for the Windows AMD64 case, I saw a check for the presence of a cmp instruction. In addition to what you said, it is also required that this instruction be located at a 4-byte-aligned address.

**Comment by husker-dev** [comment]
@avduckart 
I also decided to place this instruction after the `jmp` so that it would not be executed at all. And yes, 4-byte-aligned with `nop`

**Comment by husker-dev** [comment]
For future readers, here is my implementation:
https://github.com/husker-dev/native-kt/blob/122117c19f389ce47585a6630ab5192cdcc03aa5/native-kt-runtime-jvm/src/main/java/com/huskerdev/nativekt/jvmci/conventions/AMD64WindowsCallingConvention.java#L251
